const threatsData = [
    {
		title: 'criminal', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'disasters (natural / man-made)', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'drugs and alcohol', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'hate logos', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'obscene / disgust', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'malware', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'medical / illness', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'safe', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'sexually charged', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	},
	{
		title: 'violence and gore', 
		description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 
		images: [
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
			'https://picsum.photos/id/1071/250/150',
		],
		terms: [ 
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
			'placeholder text',
		],
	}
] 

export default threatsData; 